Add new gas metering method: mutable global + local `gas` function
paritytech/wasm-instrument pull request #34
Opened 2022-10-06 15:22 UTC by agryaznov

Solves #11 

In addition to method used beforehand (i.e. injection of calls to an imported `gas` function into metering blocks), this new method now available too, which:
- Injects an exported mutable global into the module, which tracks the gas left. 
- Injects the local `gas` function which subtracts the gas spent from the global, and drops `unreachable` if out of gas.

This new method should make the resulting module more efficient in terms of execution time, as invoking an imported `gas` host function every metering block adds an overhead. Synchronization between the global and the runtime should be implemented on the execution engine side.

2022-10-10 13:21 UTC, athei requested changes

2022-10-10 13:21 UTC, athei commented on src/gas_metering/mod.rs
> +}
The whole point of the `GasMeterable` trait was to not have to make this `match` and have two different functions. Instead, have a single generic one. The `GasMeterable` trait makes no sense. Should be something like this:

```rust
trait Backend {
    fn inject(module: &mut Module,  blocks: Vec<MeteredBlock>) -> Result<(), ()> {}
}
```

2022-10-10 13:21 UTC, athei commented on src/gas_metering/mod.rs
> +}
We don't need this anymore after we fixed trait.

2022-10-10 13:21 UTC, athei commented on src/gas_metering/mod.rs
> +) -> Result<elements::Module, elements::Module> {
After fixing the trait it would probably look like this:

```suggestion
pub fn inject<R: Rules, G: Backend>(
	input_module: Module,
	rules: &R,
	backend: G,
) -> Result<elements::Module, elements::Module> {
```

2022-10-11 07:30 UTC, agryaznov commented on src/gas_metering/mod.rs
> +}
Well, to me this looks more like an associated function than a generic function. Do you mean to have a trait assosiated function with a default implementation? Then we'll have to add two different types like this

```rust
pub struct MutableGlobalInjector; // will have the default inject() implementation containing the new logic
pub struct ImportedFunctionInjector;

impl Backend for ImportedFunctionInjector {
  // this implementation will have the old injector logic
  fn inject(module: &mut Module,  blocks: Vec<MeteredBlock>) -> Result<(), ()> {}
}
```

Is that what you're suggesting?

2022-10-11 08:01 UTC, athei commented on src/gas_metering/mod.rs
> +}
I think what you want is
```rust
impl Backend for MeteringMethod {}
```

2022-10-14 12:43 UTC, athei commented on src/gas_metering/mod.rs
> +	fn prepare(&mut self, module: &mut elements::Module) -> (u32, u32);
I think you only need this single function. Like this:

```rust
fn prepare(&mut self, module: &mut builder::ModuleBuilder) -> GasFunc;


enum GasFunc {
    External { module: String, name: String },
    Internal { definition: element::FunctionDefinition },
}
```

The injection and index calculation etc. should **not** be done in the backend. We also need to document the expected signature of the function here.

2022-10-14 12:43 UTC, athei commented on src/gas_metering/host_func.rs
> +		*module = mbuilder.build();
You don't really need to build. They are added at the end. So you could just count before and add one.

2022-10-14 12:43 UTC, athei commented on src/gas_metering/mut_global.rs
> +		*module = mbuilder.build();
As above no need to build. You can just add one. I also think we should just pass in a `&mut ModuleBuilder` so we don't need to build multiple times.

2022-10-14 12:43 UTC, athei commented on src/gas_metering/mod.rs
> +/// measurable in terms of gas consumption.
This text doesn't really help me understanding what the backend does.

2022-10-14 12:43 UTC, athei commented on src/gas_metering/mod.rs
> +mod mut_global;
Let's create a module `backend` where `Backend` trait lives and this one will then have those here as modules. Will give it a bit more structure.

2022-10-14 12:43 UTC, athei commented on src/gas_metering/mut_global.rs
> +				Instruction::I64LtS,
We treat the `gas_limit` as unsigned value. Hence you should compare and then substract. This will also make the code a bit simpler since you don't need to restore the result I think.

2022-10-14 12:46 UTC, agryaznov commented on Cargo.toml
> +bench = false
because of [this](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options)

2022-10-15 11:50 UTC, agryaznov commented
updated all but benches

2022-10-16 09:22 UTC, athei commented on src/gas_metering/backend.rs
> +	fn gas_meter(self, module: elements::Module) -> GasMeter;
```suggestion
	fn gas_meter(self, module: &elements::Module) -> GasMeter;
```

I see no reason why this should take the module by value.

2022-10-16 09:22 UTC, athei commented on src/gas_metering/mod.rs
> +	let gas_func = backend.gas_meter(module.clone());
```suggestion
	let gas_func = backend.gas_meter(&module);
```

2022-10-16 09:22 UTC, athei commented on src/gas_metering/mod.rs
> +	let mut mbuilder = builder::from_module(module.clone());
You could move all the things you need to run on `module` before this line and cache their outputs in variables. Cloning the whole module is not a good idea.

2022-10-16 09:22 UTC, athei commented on src/gas_metering/mut_global.rs
> +				Instruction::I64LtS,
Still not addressed I think.

2022-10-31 11:34 UTC, athei commented on Cargo.toml
> +parity-wasm = { version = "0.45", features = ["multi_value"] }
There shouldn't be anything requiring `multi_value` hopefully. If it is required for some test we should look into that. Additionally,  you removed `default-features = false` which breaks `no_std` builds.

2022-10-31 11:35 UTC, agryaznov commented
## Benches
showing following results on my laptop currently:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">fixture</th>
<th scope="col" class="org-left">host func</th>
<th scope="col" class="org-left">mut global</th>
<th scope="col" class="org-right">perf</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">Coremark</td>
<td class="org-left">21.126 s</td>
<td class="org-left">16.865 s</td>
<td class="org-right">+25%</td>
</tr>


<tr>
<td class="org-left">bare_call_16</td>
<td class="org-left">2.6139 ms</td>
<td class="org-left">2.8399 ms</td>
<td class="org-right">-8%</td>
</tr>


<tr>
<td class="org-left">fib_recursive</td>
<td class="org-left">9.0243 µs</td>
<td class="org-left">11.396 µs</td>
<td class="org-right">-21%</td>
</tr>


<tr>
<td class="org-left">fact_recursive</td>
<td class="org-left">1.2354 µs</td>
<td class="org-left">1.5981 µs</td>
<td class="org-right">-23%</td>
</tr>
</tbody>
</table>

2022-10-31 11:38 UTC, agryaznov commented on Cargo.toml
> +parity-wasm = { version = "0.45", features = ["multi_value"] }
yeah, it's just `bare_call_16` fixture taken from wasmi benches which requires `multi_value`.

We can replace it with some other if it's an issue.

2022-11-10 19:19 UTC, agryaznov commented
Just figured out that applying current implementation of `stack_limiter` injector after `gas_metering::mutable_global` injector bloats the resulting module massively. The reason is that with current impl of `stack_limiter` its wraps every call to the local gas function with its stack cost metering instructions. For [`many_blocks.wasm`](https://github.com/paritytech/wasm-instrument/blob/master/benches/fixtures/many_blocks.wasm) the overhead is `10x` times of original module size.

Gotta improve the `stack_limiter` to deal with the module instrumented with `mutable_global` gas metering, properly. Possible solution could be e.g. to generate a [thunk](https://github.com/paritytech/wasm-instrument/blob/ag-gas-metering/src/stack_limiter/thunk.rs#L20) for the local gas function and replace all the calls to the local gas function with calls to the thunk.

2022-11-10 19:56 UTC, athei commented
Yes good catch. However, not very important because we don't have any use case where we use both. Contracts only uses gas metering. PVF only uses stack height metering. But yes in the general case we need to deal with this interaction.

The thunk solution sounds good. If you think about this it is a nice optimization for every function that is called a lot of times. There is a certain threshold of how often a function is called where thunking it is better (smaller code is also faster code). So maybe instead of thunking a specific function we should allow passing in a threshold at which a function will be thunked.

2022-11-12 18:29 UTC, athei commented on src/gas_metering/backend.rs
> +				Instruction::I64Sub,
This cost should be statically added at the calling side. Here it causes overhead and also can make the value go negative by doing that before the check.

2022-11-12 18:34 UTC, athei reviewed
Let's do not support more work in the gas function as necessary.

2022-11-15 13:59 UTC, athei commented on src/gas_metering/mod.rs
> +				}
How is this "inlining" any useful if we call into the function anyways?

2022-11-16 19:38 UTC, agryaznov commented on src/gas_metering/mod.rs
> +				}
indeed

2022-11-17 10:07 UTC, agryaznov commented
With new wasmi engine, the overheads of calling an imported function and a local function are roughly the same. So the performance wins of using the new gas metering method are in question, and should be sanity-checked for each particular execution engine. Benchmarks are added showing how this could be measured. Versus using an emulated host function they show 11-72% performance decrease and up to 29% increase of the instrumented module size. However, these performance numbers should not be treated as the ultimate truth, as in a real world setup it deeply depends on the host function implementation and where the execution engine resides. Client-side execution engine is expected to have slower host functions, so that's could be a proper use case for the new gas metering method with a mutable global.

This problem: 

> Just figured out that applying current implementation of `stack_limiter` injector after `gas_metering::mutable_global` injector bloats the resulting module massively. The reason is that with current impl of `stack_limiter` its wraps every call to the local gas function with its stack cost metering instructions. For [`many_blocks.wasm`](https://github.com/paritytech/wasm-instrument/blob/master/benches/fixtures/many_blocks.wasm) the overhead is `10x` times of original module size.

will be addressed in a follow-up PR.

2022-11-18 12:48 UTC, agryaznov commented
# Benches
**version tested**: 6f43fbc

## with `rustc 1.65`, `wasmi 0.20.0`

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">fixture</th>
<th scope="col" class="org-left">host func</th>
<th scope="col" class="org-left">mut global</th>
<th scope="col" class="org-right">perf</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">coremark</td>
<td class="org-left">20.81 s</td>
<td class="org-left">20.20 s</td>
<td class="org-right">+3%</td>
</tr>


<tr>
<td class="org-left">recursive_ok</td>
<td class="org-left">367 µs</td>
<td class="org-left">585 µs</td>
<td class="org-right">-37%</td>
</tr>


<tr>
<td class="org-left">fibonacci_recursive</td>
<td class="org-left">9.15 µs</td>
<td class="org-left">13.56 µs</td>
<td class="org-right">-33%</td>
</tr>


<tr>
<td class="org-left">factorial_recursive</td>
<td class="org-left">1.50 µs</td>
<td class="org-left">1.98 µs</td>
<td class="org-right">-24%</td>
</tr>


<tr>
<td class="org-left">count_until</td>
<td class="org-left">5.03 ms</td>
<td class="org-left">8.13 ms</td>
<td class="org-right">-38%</td>
</tr>


<tr>
<td class="org-left">memory_vec_add</td>
<td class="org-left">6.21 ms</td>
<td class="org-left">8.45 ms</td>
<td class="org-right">-27%</td>
</tr>


<tr>
<td class="org-left">tiny_keccak</td>
<td class="org-left">925 µs</td>
<td class="org-left">1080 µs</td>
<td class="org-right">-14%</td>
</tr>


<tr>
<td class="org-left">global_bump</td>
<td class="org-left">3.79 ms</td>
<td class="org-left">7.03 ms</td>
<td class="org-right">-46%</td>
</tr>
</tbody>
</table>

2022-11-18 14:01 UTC, athei commented on src/gas_metering/mod.rs
> +	};
Mutability makes reasoning harder.

```suggestion
	let gas_fn_cost = if let GasMeter::Internal { global: _, function: _, cost, .. } = &gas_meter {
		gas_fn_cost = *cost;
	} else {
	        0
	};
```

2022-11-18 14:02 UTC, athei commented on src/gas_metering/mod.rs
> +	// Iterate over module sections and perform needed transformations
I would appreciate some comment here why we only need to do fixups for the `External` case.

2022-11-18 14:06 UTC, athei commented on src/gas_metering/mod.rs
> +	}
Again: This comment just describes the obvious. The **why** is what the reader is interested in. For example, why are we adding it here and not above where we already have a builder.

I know the reason (you don't want the fixup to apply). But it is still a non trivial information. I think this should be removed to avoid re-parsing the whole module. Just skip this function when instrumenting (so the function is not gas metered itself).

2022-11-18 14:19 UTC, athei commented on src/gas_metering/mod.rs
> +}
Let's not do that. Converting between builder and module is non trivial. See comment above. Yes, `add_grow_counter` does the same and it is not ideal. But we don't really use that in contracts right now.

2022-11-18 14:21 UTC, athei commented on tests/diff.rs
> +	def_gas_test!((branch_host_fn, branch_mut_global));
The fixtures are the same only the expectation is different. I think the macro should be written in a way that it uses the same fixture but compares it against a different expection. No need to duplicate all the inputs.

2022-11-18 19:37 UTC, agryaznov commented on tests/diff.rs
> +	def_gas_test!((ifs, ifs_host_fn, ifs_mut_global));
ugly, I know :\

[`std::concat_idents!`](https://doc.rust-lang.org/std/macro.concat_idents.html) could help here, but it's `nightly-only`

2022-11-20 13:46 UTC, athei approved these changes

2022-11-20 14:00 UTC, merged